#+title: Emacs From Scratch Configuration
#+STARTUP: content
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Startup Performance
** Ignore Annoying Message 
#+begin_src emacs-lisp
  ;;; init.el --- Generated by Emacs.org
  ;;; Commentary:
  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!
  (setq warning-suppress-types '((comp) (native-comp)))
  (setq inhibit-startup-message t)
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
** Measure Loading Time Performance
#+begin_src emacs-lisp
  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 128 1000 1000))

  (defun bc/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
	     (format "%.2f seconds"
		     (float-time
		      (time-subtract after-init-time before-init-time)))
	     gcs-done))

  (add-hook 'emacs-startup-hook #'bc/display-startup-time)
#+end_Src


* Package System Setup
** Straight.el
straight.el: next-generation, purely functional package manager for the Emacs
hacker.

#+begin_src emacs-lisp
      (defvar bootstrap-version)
      (let ((bootstrap-file
	     (expand-file-name
	      "straight/repos/straight.el/bootstrap.el"
	      (or (bound-and-true-p straight-base-dir)
		  user-emacs-directory)))
	    (bootstrap-version 7))
	(unless (file-exists-p bootstrap-file)
	  (with-current-buffer
	      (url-retrieve-synchronously
	       "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	       'silent 'inhibit-cookies)
	    (goto-char (point-max))
	    (eval-print-last-sexp)))
	(load bootstrap-file nil 'nomessage))
  ;;By default, use-package uses package.el to install packages
  ;;To configure use-package to always use straight.el, use use-package to configure straight.el
  ;;to turn on straight-use-package-by-default.
    (use-package straight
      :ensure nil
      :custom
      (straight-use-package-by-default t))

#+end_src

* Basic Setup
** Keep Folders Clean
use the no-littering package to keep folders where we edit files and the Emacs
configuration folder clean! It knows about a wide variety of variables for built
in Emacs features as well as those from community packages so it can be much
easier than finding and setting these variables yourself.

#+begin_src emacs-lisp
  (use-package no-littering
    :straight t
    :config
    (require 'recentf)
    (add-to-list 'recentf-exclude no-littering-var-directory)
    (add-to-list 'recentf-exclude no-littering-etc-directory)

    ;; no-littering doesn't set this by default so we must place
    ;; auto save files in the same path as it uses for sessions
    (setq auto-save-file-name-transforms
	  `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

    ;; Emacs will save customizations into your init.el file by default. If you don't
    ;; want that, you might want to store them in a sibling file or even in the etc/
    ;; directory:

    (setq custom-file (no-littering-expand-etc-file-name "custom.el"))
    )
  (setq make-backup-files nil)
#+end_src

** Auto Wrap lines
#+begin_src emacs-lisp
(global-visual-line-mode 1)
#+end_src

** Window Switch
#+begin_src emacs-lisp
  (use-package ace-window
    :straight t)
  (global-set-key (kbd "M-o") 'ace-window)
#+end_src

** Evil Mode
Evil is an extensible vi layer for Emacs. It emulates the main features of Vim,
turning Emacs into a modal editor. Like Emacs in general, Evil is extensible in
Emacs Lisp.

#+begin_src emacs-lisp
  (use-package evil
    :straight t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :straight t
    :after evil
    :config
    (evil-collection-init))

  (use-package evil-nerd-commenter
    :straight t
    :config
    (evilnc-default-hotkeys))

  ;; (use-package evil-matchit
  ;; :straight t
  ;; :config
  ;; (global-evil-matchit-mode 1))
  
#+end_src

** Which Key 

#+begin_src emacs-lisp
  (use-package general
    :straight t
    :config
    (general-define-key
     :prefix "SPC"
     :states '(normal visual)
     "f" 'find-file
     "b" 'switch-to-buffer
     "w" 'save-buffer
     ;; 更多自定义命令...
     ))

    (use-package which-key
    :straight t
    :config
    (which-key-mode)  ;; Enable which-key
    (setq which-key-idle-delay 0.5)  ;; Show keybinding hints after a short delay
    (setq which-key-popup-type 'side-window)  ;; Display keybindings in a side window (other options: 'mini-window)
    (setq which-key-side-window-location 'right)  ;; Position the popup on the right side of the screen
    (setq which-key-max-description-length 30)  ;; Max length for descriptions in the popup
    (setq which-key-min-display-lines 10)  ;; Show at least 10 lines in the popup
    (setq which-key-show-early-on-C-h t)  ;; Show keybindings as soon as you press `C-h`
  )
#+end_src

** Ivy & Counsel
Ivy is an excellent completion framework for Emacs. It provides a minimal yet
powerful selection menu that appears when you open files, switch buffers, and
for many other tasks in Emacs. Counsel is a customized set of commands to
replace `find-file` with `counsel-find-file`, etc which provide useful commands
for each of the default completion commands.

ivy-rich adds extra columns to a few of the Counsel commands to provide more
information about each item.

#+begin_src emacs-lisp
  (use-package ivy
  :straight t
    :bind (
	     ("C-s" . swiper)
	     :map ivy-minibuffer-map
	     ("TAB" . ivy-alt-done)
	     ("C-l" . ivy-alt-done)
	     ("C-j" . ivy-next-line)
	     ("C-k" . ivy-previous-line)
	     :map ivy-switch-buffer-map
	     ("C-k" . ivy-previous-line)
	     ("C-l" . ivy-done)
	     ("C-d" . ivy-switch-buffer-kill)
	     :map ivy-reverse-i-search-map
	     ("C-k" . ivy-previous-line)
	     ("C-d" . ivy-reverse-i-search-kill))
    :config
    (setq ivy-use-virtual-buffers t)
    (setq ivy-wrap t)
    (setq ivy-count-format "(%d/%d) ")
    (setq enable-recursive-minibuffers t)

    (setq ivy-initial-inputs-alist nil)

    ;; Use different regex strategies per completion command
    ;; (push '(completion-at-point . ivy--regex-fuzzy) ivy-re-builders-alist)
    (push '(swiper . ivy--regex-ignore-order) ivy-re-builders-alist)
    (push '(counsel-M-x . ivy--regex-ignore-order) ivy-re-builders-alist)

    ;; Set minibuffer height for different commands
    (setf (alist-get 'counsel-projectile-ag ivy-height-alist) 15)
    (setf (alist-get 'counsel-projectile-rg ivy-height-alist) 15)
    (setf (alist-get 'swiper ivy-height-alist) 15)
    (setf (alist-get 'counsel-switch-buffer ivy-height-alist) 7)

    (ivy-mode 1))

  (use-package counsel
    :straight t
    :bind (("M-x" . counsel-M-x)
	     ("C-x b" . counsel-switch-buffer)
	     ("C-M-j" . 'counsel-switch-buffer)
	     ("C-x C-b" . counsel-ibuffer)
	     ("M-y" . counsel-yank-pop)
	     ("C-x C-r" . counsel-recentf)
	     ("C-x C-f" . counsel-find-file)
	     :map minibuffer-local-map
	     ("C-r" . 'counsel-minibuffer-history))
    ;;:custom
    ;;(counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src


* Org Mode
** Format Org File
#+begin_src emacs-lisp
  (setq-default fill-column 80)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
#+end_src
